<?php

namespace AppBundle\Repository;

/**
 * CommanditaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommanditaireRepository extends \Doctrine\ORM\EntityRepository
{
}
